Maybe fix darwin compile error.
  external/checkpolicy/policy_define.c:63: error: 'PATH_MAX' undeclared here (not in a function)
  [deleted]
  make: *** [out/host/darwin-x86/obj/EXECUTABLES/checkpolicy_intermediates/policy_define.o] Error 1
  make: *** Waiting for unfinished jobs....

(cherry picked from commit 0bbc7a9cf9c0bd96b932d903d6a781d8de323ea5)

Change-Id: I2f2265dab232c3fd74f7793ab45c198843f75c74